# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/node:17.1.0
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "package.json"}}
      - run:
          command: npm i
      - save_cache:
          key: package-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run:
          command: npm run lint
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint
